-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 14:08:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema logistics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logistics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logistics` DEFAULT CHARACTER SET utf8 ;
USE `logistics` ;

-- -----------------------------------------------------
-- Table `logistics`.`points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics`.`points` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics`.`road`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics`.`road` (
  `point1_id` BIGINT NOT NULL,
  `point2_id` BIGINT NOT NULL,
  `distance` DOUBLE NOT NULL,
  PRIMARY KEY (`point1_id`, `point2_id`),
  INDEX `fk_road_points2_idx` (`point2_id` ASC) VISIBLE,
  CONSTRAINT `fk_road_points1`
    FOREIGN KEY (`point1_id`)
    REFERENCES `logistics`.`points` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_road_points2`
    FOREIGN KEY (`point2_id`)
    REFERENCES `logistics`.`points` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics`.`car_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics`.`car_model` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `tonnage` DOUBLE NOT NULL,
  `space` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics`.`users` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(50) NULL,
  `surname` VARCHAR(50) NULL,
  `phone` VARCHAR(15) NULL,
  `e_mail` VARCHAR(50) NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics`.`role` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics`.`transporter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics`.`transporter` (
  `user_id` BIGINT NOT NULL,
  `license` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `license_UNIQUE` (`license` ASC) VISIBLE,
  CONSTRAINT `fk_transporter_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `logistics`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics`.`transporter_car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics`.`transporter_car` (
  `id` BIGINT NOT NULL,
  `car_model_id` BIGINT NOT NULL,
  `transporter_id` BIGINT NOT NULL,
  `point_id` BIGINT NOT NULL,
  `cost_mult` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_car_transporter_id_idx` (`transporter_id` ASC) VISIBLE,
  INDEX `fk_car_car_model_id_idx` (`car_model_id` ASC) VISIBLE,
  INDEX `fk_car_points_id_idx` (`point_id` ASC) VISIBLE,
  CONSTRAINT `fk_car_car_model_id`
    FOREIGN KEY (`car_model_id`)
    REFERENCES `logistics`.`car_model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_transporter_id`
    FOREIGN KEY (`transporter_id`)
    REFERENCES `logistics`.`transporter` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_points_id`
    FOREIGN KEY (`point_id`)
    REFERENCES `logistics`.`points` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics`.`users_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics`.`users_has_role` (
  `users_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`users_id`, `role_id`),
  INDEX `fk_users_has_role_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_users_has_role_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_role_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `logistics`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `logistics`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
